#:schema node_modules/wrangler/config-schema.json
name = "www"
compatibility_date = "2024-08-15"
pages_build_output_dir = "./build/client"

services = [
  { binding = "api", service = "willhackett-api" }
]

[placement]
mode = "smart"