#:schema node_modules/wrangler/config-schema.json
name = "www"
compatibility_date = "2024-08-15"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[vars]
GRAPHQL_URI = "http://localhost:8787/"


[env.production.vars]
GRAPHQL_URI = "https://api.willhackett.com/"
