#:schema node_modules/wrangler/config-schema.json
name = "www"
compatibility_date = "2024-08-21"
pages_build_output_dir = "./build/client"

services = [
  { binding = "api", service = "api" },
]

[placement]
mode = "smart"
